# Generated by Django 4.0.6 on 2022-07-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Digite seu email'),
        ),
    ]
