# Generated by Django 4.0.6 on 2022-07-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_alter_receita_foto_receita_alter_receita_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
